Issues a warning when a function is not collected as a test case just because it uses :py:func:`@pytest.fixture`
